name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Replace with your Python version
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m unittest tests/test_my_model.py # Adapt to your testing framework
      - name: Generate report (Example - adapt as needed)
        run: |
          python src/my_model.py > report.txt # Replace with your report generation command
          echo "Report generated: report.txt"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # Make sure 'docs' directory exists
